# Data Wrangling

In [1]:
import pandas as pd
import numpy as np
import quandl
import time

In [2]:
# Access quandl with API key
quandl.ApiConfig.api_key = "hCxi5g-8hmVb2oihz2ek"

I obtained the tickers from a list on [Wikipedia](https://en.wikipedia.org/wiki/List_of_S%26P_500_companies).

In [3]:
sptickers = ['MMM','ABT','ABBV','ACN','ATVI','AYI','ADBE','AMD','AAP','AES','AET',
		'AMG','AFL','A','APD','AKAM','ALK','ALB','ARE','ALXN','ALGN','ALLE',
		'AGN','ADS','LNT','ALL','GOOGL','GOOG','MO','AMZN','AEE','AAL','AEP',
		'AXP','AIG','AMT','AWK','AMP','ABC','AME','AMGN','APH','APC','ADI','ANDV',
		'ANSS','ANTM','AON','AOS','APA','AIV','AAPL','AMAT','APTV','ADM','ARNC',
		'AJG','AIZ','T','ADSK','ADP','AZO','AVB','AVY','BHGE','BLL','BAC','BK',
		'BAX','BBT','BDX','BRK.B','BBY','BIIB','BLK','HRB','BA','BWA','BXP','BSX',
		'BHF','BMY','AVGO','BF.B','CHRW','CA','COG','CDNS','CPB','COF','CAH','CBOE',
		'KMX','CCL','CAT','CBG','CBS','CELG','CNC','CNP','CTL','CERN','CF','SCHW',
		'CHTR','CHK','CVX','CMG','CB','CHD','CI','XEC','CINF','CTAS','CSCO','C','CFG',
		'CTXS','CLX','CME','CMS','KO','CTSH','CL','CMCSA','CMA','CAG','CXO','COP',
		'ED','STZ','COO','GLW','COST','COTY','CCI','CSRA','CSX','CMI','CVS','DHI',
		'DHR','DRI','DVA','DE','DAL','XRAY','DVN','DLR','DFS','DISCA','DISCK','DISH',
		'DG','DLTR','D','DOV','DWDP','DPS','DTE','DRE','DUK','DXC','ETFC','EMN','ETN',
		'EBAY','ECL','EIX','EW','EA','EMR','ETR','EVHC','EOG','EQT','EFX','EQIX','EQR',
		'ESS','EL','ES','RE','EXC','EXPE','EXPD','ESRX','EXR','XOM','FFIV','FB','FAST',
		'FRT','FDX','FIS','FITB','FE','FISV','FLIR','FLS','FLR','FMC','FL','F','FTV',
		'FBHS','BEN','FCX','GPS','GRMN','IT','GD','GE','GGP','GIS','GM','GPC','GILD',
		'GPN','GS','GT','GWW','HAL','HBI','HOG','HRS','HIG','HAS','HCA','HCP','HP','HSIC',
		'HSY','HES','HPE','HLT','HOLX','HD','HON','HRL','HST','HPQ','HUM','HBAN','HII',
		'IDXX','INFO','ITW','ILMN','IR','INTC','ICE','IBM','INCY','IP','IPG','IFF','INTU',
		'ISRG','IVZ','IQV','IRM','JEC','JBHT','SJM','JNJ','JCI','JPM','JNPR','KSU','K','KEY',
		'KMB','KIM','KMI','KLAC','KSS','KHC','KR','LB','LLL','LH','LRCX','LEG','LEN','LUK',
		'LLY','LNC','LKQ','LMT','L','LOW','LYB','MTB','MAC','M','MRO','MPC','MAR','MMC','MLM',
		'MAS','MA','MAT','MKC','MCD','MCK','MDT','MRK','MET','MTD','MGM','KORS','MCHP','MU',
		'MSFT','MAA','MHK','TAP','MDLZ','MON','MNST','MCO','MS','MOS','MSI','MYL','NDAQ',
		'NOV','NAVI','NTAP','NFLX','NWL','NFX','NEM','NWSA','NWS','NEE','NLSN','NKE','NI',
		'NBL','JWN','NSC','NTRS','NOC','NCLH','NRG','NUE','NVDA','ORLY','OXY','OMC','OKE',
		'ORCL','PCAR','PKG','PH','PDCO','PAYX','PYPL','PNR','PBCT','PEP','PKI','PRGO','PFE',
		'PCG','PM','PSX','PNW','PXD','PNC','RL','PPG','PPL','PX','PCLN','PFG','PG','PGR',
		'PLD','PRU','PEG','PSA','PHM','PVH','QRVO','PWR','QCOM','DGX','RRC','RJF','RTN','O',
		'RHT','REG','REGN','RF','RSG','RMD','RHI','ROK','COL','ROP','ROST','RCL','CRM','SBAC',
		'SCG','SLB','SNI','STX','SEE','SRE','SHW','SIG','SPG','SWKS','SLG','SNA','SO','LUV',
		'SPGI','SWK','SBUX','STT','SRCL','SYK','STI','SYMC','SYF','SNPS','SYY','TROW','TPR',
		'TGT','TEL','FTI','TXN','TXT','TMO','TIF','TWX','TJX','TMK','TSS','TSCO','TDG','TRV',
		'TRIP','FOXA','FOX','TSN','UDR','ULTA','USB','UAA','UA','UNP','UAL','UNH','UPS','URI',
		'UTX','UHS','UNM','VFC','VLO','VAR','VTR','VRSN','VRSK','VZ','VRTX','VIAB','V','VNO',
		'VMC','WMT','WBA','DIS','WM','WAT','WEC','WFC','HCN','WDC','WU','WRK','WY','WHR','WMB',
		'WLTW','WYN','WYNN','XEL','XRX','XLNX','XL','XYL','YUM','ZBH','ZION','ZTS']

len(sptickers)

505

For simplicity, I use Quandl's WIKI Price [database](https://www.quandl.com/databases/WIKIP/documentation). Note that the database is not completely up-to-date.

In [4]:
# Create index for data frame. Dates from 1999-01-01 to 2019-01-01.

index = pd.date_range(start='1999-01-01', end='2019-01-01')
sp500 = pd.DataFrame(index=index)

# Because I can't make too many requests at once, I run a loop through the tickers
for i in sptickers:
    data = quandl.get_table('WIKI/PRICES', ticker = i, 
                        qopts = { 'columns': ['ticker', 'date', 'adj_close'] }, 
                        date = { 'gte': '1999-01-01', 'lte': '2019-01-01' }, 
                        paginate=True)
    
    # Set the row index to date and fill in the ticker
    new = data.set_index('date')
    clean_data = new.pivot(columns='ticker')
    sp500 = sp500.join(clean_data, how="left")
    # Counter for the impatient
    time.sleep(.1)

/anaconda3/lib/python3.7/site-packages/pandas/core/reshape/merge.py:522: UserWarning: merging between different levels can give an unintended result (1 levels on the left, 2 on the right)
  warnings.warn(msg, UserWarning)

In [5]:
# Drop all observations where the market is not open
sp500 = sp500.dropna(axis=0,how='all')
# Clean up the column names
sp500.columns = [i[1] for i in sp500.columns]

# S&P 500 Indicators
Let's just see what kind of data we can get from SHARADAR. I'll test it using Apple (AAPL).

In [6]:
data = quandl.get_table('SHARADAR/SF1', ticker = 'AAPL')
data

,ticker,dimension,calendardate,datekey,reportperiod,lastupdated,accoci,assets,assetsavg,assetsc,...,sharesbas,shareswa,shareswadil,sps,tangibles,taxassets,taxexp,taxliabilities,tbvps,workingcapital
None,,,,,,,,,,,,,,,,,,,,,
0,AAPL,MRY,2018-12-31,2018-09-29,2018-09-29,2019-05-01,-3454000000,365725000000,372304500000,131339000000,...,4829926000,4955377000,5000109000,53.597,365725000000,0,13372000000,0,76.168,15410000000
1,AAPL,MRY,2017-12-31,2017-09-30,2017-09-30,2019-05-01,-150000000,375319000000,346541250000,128645000000,...,5165228000,5217242000,5251692000,43.938,375319000000,0,15738000000,0,72.886,27831000000
2,AAPL,MRY,2016-12-31,2016-09-24,2016-09-24,2019-05-01,634000000,321686000000,306462250000,106869000000,...,5388443000,5470820000,5500281000,39.416,313066000000,0,15685000000,0,58.333,27863000000
3,AAPL,MRY,2015-12-31,2015-09-26,2015-09-26,2019-05-01,-345000000,290345000000,271646000000,89378000000,...,5702722000,5753421000,5793069000,40.622,281336000000,0,19121000000,0,49.821,8768000000
4,AAPL,MRY,2014-12-31,2014-09-27,2014-09-27,2019-05-01,1082000000,231839000000,221383000000,68531000000,...,5987867000,6085572000,6122663000,30.037,223081000000,4318000000,13973000000,0,37.595,5083000000
5,AAPL,MRY,2013-12-31,2013-09-28,2013-09-28,2019-05-01,-471000000,207000000000,199421750000,73286000000,...,6359479000,6477320000,6521634000,26.386,201244000000,3453000000,13118000000,0,31.796,29628000000
6,AAPL,MRY,2012-12-31,2012-09-29,2012-09-29,2019-05-01,499000000,176064000000,157143750000,57653000000,...,6561842000,6543726000,6617483000,23.917,170705000000,2583000000,14030000000,0,25.991,19111000000
7,AAPL,MRY,2011-12-31,2011-09-24,2011-09-24,2019-05-01,443000000,116371000000,101193750000,44988000000,...,6489636202,6469806000,6556515000,16.731,111939000000,2014000000,8283000000,0,17.227,17018000000

It seems that, without paying, I can get up to 8 time periods of Most-Recently Reported Yearly Data (MRY). The documentation defines Most-Recently Reported as "the most recently reported data for that reporting period."

In [7]:
# Create empty dataframe to store results
indicators = pd.DataFrame(columns = data.columns)

# Go through all tickers and get the indicators
for ticker in sptickers:
    data = quandl.get_table('SHARADAR/SF1', ticker = ticker)
    indicators = indicators.append(data)
    time.sleep(.1)

In [8]:
indicators.head()

,ticker,dimension,calendardate,datekey,reportperiod,lastupdated,accoci,assets,assetsavg,assetsc,...,sharesbas,shareswa,shareswadil,sps,tangibles,taxassets,taxexp,taxliabilities,tbvps,workingcapital
0,MMM,MRY,2018-12-31,2018-12-31,2018-12-31,2019-04-26,-6866000000,36500000000,37282000000,13709000000,...,582287135,588500000,602000000,55.675,23792000000,0,1637000000,243000000,40.971,6465000000
1,MMM,MRY,2017-12-31,2017-12-31,2017-12-31,2019-04-26,-7026000000,37987000000,35118250000,14277000000,...,595608108,597500000,612700000,52.982,24538000000,0,2679000000,310000000,41.15,6590000000
2,MMM,MRY,2016-12-31,2016-12-31,2016-12-31,2019-04-26,-7245000000,32906000000,33293500000,11726000000,...,601466401,604700000,618700000,49.792,21420000000,0,1995000000,299000000,35.688,5507000000
3,MMM,MRY,2015-12-31,2015-12-31,2015-12-31,2019-04-26,-6359000000,32883000000,32043000000,10986000000,...,615712937,625600000,637200000,48.392,21033000000,0,1982000000,332000000,34.245,3868000000
4,MMM,MRY,2014-12-31,2014-12-31,2014-12-31,2019-04-26,-6289000000,31209000000,32875500000,12303000000,...,640818842,649200000,662000000,49.016,22724000000,0,2028000000,435000000,35.612,6339000000

# Data Preparation

## 1) Accounting for Stock Splits
Stock splits cause an increase in the supply of the stock while the company value remains the same. Typically this is done 2 to 1. Meaning, if you hold 10 stocks of AAPL priced at 150 each, it will become 20 stocks priced at 75 each. Unaccounted for, it would lead to a drastic decrease.

In [9]:
# Set up index
index = pd.date_range(start='1999-01-01', end='2019-01-01')
stock_splits = pd.DataFrame(index=index)

# Get split ratios one company at a time
for i in sptickers:
    split = quandl.get_table('WIKI/PRICES', ticker = i, 
                            qopts = { 'columns': ['ticker', 'date', 'split_ratio'] }, 
                            date = { 'gte': '1999-01-01', 'lte': '2019-01-01' }, 
                            paginate=True)
    # Join data to index
    new_splits = split.set_index('date')
    clean_splits = new_splits.pivot(columns='ticker')
    stock_splits = stock_splits.join(clean_splits, how="left")

In [10]:
# Clean up column names
stock_splits.columns = [i[1] for i in stock_splits.columns]

In [11]:
# Remove closed market days, and account for NaNs
stock_splits = stock_splits.dropna(axis=0, how='all')
stock_splits = stock_splits.apply(pd.to_numeric)
stock_splits = stock_splits.fillna(1)

In [12]:
# Function to create a dataframe of multiplicative factors
def split_factor(split_ratio):
    series = np.asarray(split_ratio)
    split_index = []
    # Get indices where ratio isn't one
    for i in range(len(series)):  
        if(series[i] != 1):
            split_index.append(i)
    # Start at the last value
    split_index.reverse()
    # Multiply all values after the index by the ratio
    for j in split_index:
        series[j+1:len(series)] = series[j+1:len(series)]*series[j]
    return(series)

In [13]:
# Use the above function
stock_splits.apply(split_factor)

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:13: RuntimeWarning: overflow encountered in multiply
  del sys.path[0]

,MMM,ABT,ABBV,ACN,ATVI,AYI,ADBE,AMD,AAP,AES,...,WYNN,XEL,XRX,XLNX,XL,XYL,YUM,ZBH,ZION,ZTS
1999-01-04,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1999-01-05,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1999-01-06,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1999-01-07,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1999-01-08,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1999-01-11,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1999-01-12,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1999-01-13,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1999-01-14,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1999-01-15,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1999-01-19,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1999-01-20,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1999-01-21,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1999-01-22,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1999-01-25,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1999-01-26,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1999-01-27,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1999-01-28,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1999-01-29,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1999-02-01,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1999-02-02,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1999-02-03,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1999-02-04,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1999-02-05,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1999-02-08,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1999-02-09,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1999-02-10,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1999-02-11,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1999-02-12,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1999-02-16,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-02-13,inf,1.0,1.0,1.0,12.0,1.0,8.0,2.0,3.0,2.0,...,1.0,1.0,0.5,4.0,1.0,1.0,4.0,1.0,1.0,1.0
2018-02-14,inf,1.0,1.0,1.0,12.0,1.0,8.0,2.0,3.0,2.0,...,1.0,1.0,0.5,4.0,1.0,1.0,4.0,1.0,1.0,1.0
2018-02-15,inf,1.0,1.0,1.0,12.0,1.0,8.0,2.0,3.0,2.0,...,1.0,1.0,0.5,4.0,1.0,1.0,4.0,1.0,1.0,1.0
2018-02-16,inf,1.0,1.0,1.0,12.0,1.0,8.0,2.0,3.0,2.0,...,1.0,1.0,0.5,4.0,1.0,1.0,4.0,1.0,1.0,1.0
2018-02-20,inf,1.0,1.0,1.0,12.0,1.0,8.0,2.0,3.0,2.0,...,1.0,1.0,0.5,4.0,1.0,1.0,4.0,1.0,1.0,1.0
2018-02-21,inf,1.0,1.0,1.0,12.0,1.0,8.0,2.0,3.0,2.0,...,1.0,1.0,0.5,4.0,1.0,1.0,4.0,1.0,1.0,1.0
2018-02-22,inf,1.0,1.0,1.0,12.0,1.0,8.0,2.0,3.0,2.0,...,1.0,1.0,0.5,4.0,1.0,1.0,4.0,1.0,1.0,1.0
2018-02-23,inf,1.0,1.0,1.0,12.0,1.0,8.0,2.0,3.0,2.0,...,1.0,1.0,0.5,4.0,1.0,1.0,4.0,1.0,1.0,1.0
2018-02-26,inf,1.0,1.0,1.0,12.0,1.0,8.0,2.0,3.0,2.0,...,1.0,1.0,0.5,4.0,1.0,1.0,4.0,1.0,1.0,1.0
2018-02-27,inf,1.0,1.0,1.0,12.0,1.0,8.0,2.0,3.0,2.0,...,1.0,1.0,0.5,4.0,1.0,1.0,4.0,1.0,1.0,1.0
2018-02-28,inf,1.0,1.0,1.0,12.0,1.0,8.0,2.0,3.0,2.0,...,1.0,1.0,0.5,4.0,1.0,1.0,4.0,1.0,1.0,1.0
2018-03-01,inf,1.0,1.0,1.0,12.0,1.0,8.0,2.0,3.0,2.0,...,1.0,1.0,0.5,4.0,1.0,1.0,4.0,1.0,1.0,1.0
2018-03-02,inf,1.0,1.0,1.0,12.0,1.0,8.0,2.0,3.0,2.0,...,1.0,1.0,0.5,4.0,1.0,1.0,4.0,1.0,1.0,1.0
2018-03-05,inf,1.0,1.0,1.0,12.0,1.0,8.0,2.0,3.0,2.0,...,1.0,1.0,0.5,4.0,1.0,1.0,4.0,1.0,1.0,1.0
2018-03-06,inf,1.0,1.0,1.0,12.0,1.0,8.0,2.0,3.0,2.0,...,1.0,1.0,0.5,4.0,1.0,1.0,4.0,1.0,1.0,1.0
2018-03-07,inf,1.0,1.0,1.0,12.0,1.0,8.0,2.0,3.0,2.0,...,1.0,1.0,0.5,4.0,1.0,1.0,4.0,1.0,1.0,1.0
2018-03-08,inf,1.0,1.0,1.0,12.0,1.0,8.0,2.0,3.0,2.0,...,1.0,1.0,0.5,4.0,1.0,1.0,4.0,1.0,1.0,1.0
2018-03-09,inf,1.0,1.0,1.0,12.0,1.0,8.0,2.0,3.0,2.0,...,1.0,1.0,0.5,4.0,1.0,1.0,4.0,1.0,1.0,1.0
2018-03-12,inf,1.0,1.0,1.0,12.0,1.0,8.0,2.0,3.0,2.0,...,1.0,1.0,0.5,4.0,1.0,1.0,4.0,1.0,1.0,1.0
2018-03-13,inf,1.0,1.0,1.0,12.0,1.0,8.0,2.0,3.0,2.0,...,1.0,1.0,0.5,4.0,1.0,1.0,4.0,1.0,1.0,1.0
2018-03-14,inf,1.0,1.0,1.0,12.0,1.0,8.0,2.0,3.0,2.0,...,1.0,1.0,0.5,4.0,1.0,1.0,4.0,1.0,1.0,1.0
2018-03-15,inf,1.0,1.0,1.0,12.0,1.0,8.0,2.0,3.0,2.0,...,1.0,1.0,0.5,4.0,1.0,1.0,4.0,1.0,1.0,1.0
2018-03-16,inf,1.0,1.0,1.0,12.0,1.0,8.0,2.0,3.0,2.0,...,1.0,1.0,0.5,4.0,1.0,1.0,4.0,1.0,1.0,1.0
2018-03-19,inf,1.0,1.0,1.0,12.0,1.0,8.0,2.0,3.0,2.0,...,1.0,1.0,0.5,4.0,1.0,1.0,4.0,1.0,1.0,1.0
2018-03-20,inf,1.0,1.0,1.0,12.0,1.0,8.0,2.0,3.0,2.0,...,1.0,1.0,0.5,4.0,1.0,1.0,4.0,1.0,1.0,1.0
2018-03-21,inf,1.0,1.0,1.0,12.0,1.0,8.0,2.0,3.0,2.0,...,1.0,1.0,0.5,4.0,1.0,1.0,4.0,1.0,1.0,1.0
2018-03-22,inf,1.0,1.0,1.0,12.0,1.0,8.0,2.0,3.0,2.0,...,1.0,1.0,0.5,4.0,1.0,1.0,4.0,1.0,1.0,1.0
2018-03-23,inf,1.0,1.0,1.0,12.0,1.0,8.0,2.0,3.0,2.0,...,1.0,1.0,0.5,4.0,1.0,1.0,4.0,1.0,1.0,1.0
2018-03-26,inf,1.0,1.0,1.0,12.0,1.0,8.0,2.0,3.0,2.0,...,1.0,1.0,0.5,4.0,1.0,1.0,4.0,1.0,1.0,1.0
2018-03-27,inf,1.0,1.0,1.0,12.0,1.0,8.0,2.0,3.0,2.0,...,1.0,1.0,0.5,4.0,1.0,1.0,4.0,1.0,1.0,1.0

In [14]:
# Fill NaNs and multiply to control for splits
sp500 = sp500.fillna(0)
sp500_unsplit = sp500.multiply(stock_splits)

## 2) Log-Returns
Most analyses on stock returns are done in log-returns because of the additive property they have. The sum of 10 consecutive log-returns is the same as the log-return between the first and last of those 10 periods.

In [18]:
# Define a function to keep things clean
def log_return(stock):
    log_ret = np.log(stock) - np.log(stock.shift(1))
    return(log_ret)

# Apply above function across all columns
sp500_lr = sp500_unsplit.apply(log_return)
sp500_lr.head()

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in log
  This is separate from the ipykernel package so we can avoid doing imports until

,MMM,ABT,ABBV,ACN,ATVI,AYI,ADBE,AMD,AAP,AES,...,WYNN,XEL,XRX,XLNX,XL,XYL,YUM,ZBH,ZION,ZTS
1999-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999-01-05,0.005745,0.001230,NaN,NaN,-0.006455,NaN,-0.021454,-0.011133,NaN,-0.003890,...,NaN,0.002184,0.018503,0.042135,-0.004131,NaN,0.019138,NaN,-0.001992,NaN
1999-01-06,0.045575,-0.007609,NaN,NaN,0.017424,NaN,-0.036459,-0.016018,NaN,0.000000,...,NaN,0.004716,0.018985,-0.008953,-0.057583,NaN,0.015172,NaN,0.000000,NaN
1999-01-07,-0.023309,-0.013091,NaN,NaN,-0.005469,NaN,0.020996,0.006948,NaN,-0.025975,...,NaN,-0.004716,-0.004097,-0.007279,0.018362,NaN,-0.005032,NaN,-0.007337,NaN
1999-01-08,0.004939,-0.003772,NaN,NaN,-0.011954,NaN,0.014030,0.020203,NaN,-0.037538,...,NaN,-0.006933,-0.004938,0.000876,-0.042560,NaN,0.002620,NaN,0.002173,NaN

## 3) Missing Data
I left all the NaNs as 0. This treats the period as if there are no returns. I will address the cases of the inexistence of the stock in the data story telling notebook. Usually, where there is a missing value the stock was not being traded. Normally, I would try to find a more complete dataset to validate and verify this, but unfortunately with the limitations of free data available I cannot be too picky.

In [20]:
sp500_lr.to_csv("SP500.csv")
indicators.to_csv("SP500indicators.csv")