# S&P 500 Historical Stock Data

In [5]:
import pandas as pd
import quandl
import time

In [6]:
# Access quandl with API key
quandl.ApiConfig.api_key = "hCxi5g-8hmVb2oihz2ek"

I obtained the tickers from a list on [Wikipedia](https://en.wikipedia.org/wiki/List_of_S%26P_500_companies).

In [7]:
sptickers = ['MMM','ABT','ABBV','ACN','ATVI','AYI','ADBE','AMD','AAP','AES','AET',
		'AMG','AFL','A','APD','AKAM','ALK','ALB','ARE','ALXN','ALGN','ALLE',
		'AGN','ADS','LNT','ALL','GOOGL','GOOG','MO','AMZN','AEE','AAL','AEP',
		'AXP','AIG','AMT','AWK','AMP','ABC','AME','AMGN','APH','APC','ADI','ANDV',
		'ANSS','ANTM','AON','AOS','APA','AIV','AAPL','AMAT','APTV','ADM','ARNC',
		'AJG','AIZ','T','ADSK','ADP','AZO','AVB','AVY','BHGE','BLL','BAC','BK',
		'BAX','BBT','BDX','BRK.B','BBY','BIIB','BLK','HRB','BA','BWA','BXP','BSX',
		'BHF','BMY','AVGO','BF.B','CHRW','CA','COG','CDNS','CPB','COF','CAH','CBOE',
		'KMX','CCL','CAT','CBG','CBS','CELG','CNC','CNP','CTL','CERN','CF','SCHW',
		'CHTR','CHK','CVX','CMG','CB','CHD','CI','XEC','CINF','CTAS','CSCO','C','CFG',
		'CTXS','CLX','CME','CMS','KO','CTSH','CL','CMCSA','CMA','CAG','CXO','COP',
		'ED','STZ','COO','GLW','COST','COTY','CCI','CSRA','CSX','CMI','CVS','DHI',
		'DHR','DRI','DVA','DE','DAL','XRAY','DVN','DLR','DFS','DISCA','DISCK','DISH',
		'DG','DLTR','D','DOV','DWDP','DPS','DTE','DRE','DUK','DXC','ETFC','EMN','ETN',
		'EBAY','ECL','EIX','EW','EA','EMR','ETR','EVHC','EOG','EQT','EFX','EQIX','EQR',
		'ESS','EL','ES','RE','EXC','EXPE','EXPD','ESRX','EXR','XOM','FFIV','FB','FAST',
		'FRT','FDX','FIS','FITB','FE','FISV','FLIR','FLS','FLR','FMC','FL','F','FTV',
		'FBHS','BEN','FCX','GPS','GRMN','IT','GD','GE','GGP','GIS','GM','GPC','GILD',
		'GPN','GS','GT','GWW','HAL','HBI','HOG','HRS','HIG','HAS','HCA','HCP','HP','HSIC',
		'HSY','HES','HPE','HLT','HOLX','HD','HON','HRL','HST','HPQ','HUM','HBAN','HII',
		'IDXX','INFO','ITW','ILMN','IR','INTC','ICE','IBM','INCY','IP','IPG','IFF','INTU',
		'ISRG','IVZ','IQV','IRM','JEC','JBHT','SJM','JNJ','JCI','JPM','JNPR','KSU','K','KEY',
		'KMB','KIM','KMI','KLAC','KSS','KHC','KR','LB','LLL','LH','LRCX','LEG','LEN','LUK',
		'LLY','LNC','LKQ','LMT','L','LOW','LYB','MTB','MAC','M','MRO','MPC','MAR','MMC','MLM',
		'MAS','MA','MAT','MKC','MCD','MCK','MDT','MRK','MET','MTD','MGM','KORS','MCHP','MU',
		'MSFT','MAA','MHK','TAP','MDLZ','MON','MNST','MCO','MS','MOS','MSI','MYL','NDAQ',
		'NOV','NAVI','NTAP','NFLX','NWL','NFX','NEM','NWSA','NWS','NEE','NLSN','NKE','NI',
		'NBL','JWN','NSC','NTRS','NOC','NCLH','NRG','NUE','NVDA','ORLY','OXY','OMC','OKE',
		'ORCL','PCAR','PKG','PH','PDCO','PAYX','PYPL','PNR','PBCT','PEP','PKI','PRGO','PFE',
		'PCG','PM','PSX','PNW','PXD','PNC','RL','PPG','PPL','PX','PCLN','PFG','PG','PGR',
		'PLD','PRU','PEG','PSA','PHM','PVH','QRVO','PWR','QCOM','DGX','RRC','RJF','RTN','O',
		'RHT','REG','REGN','RF','RSG','RMD','RHI','ROK','COL','ROP','ROST','RCL','CRM','SBAC',
		'SCG','SLB','SNI','STX','SEE','SRE','SHW','SIG','SPG','SWKS','SLG','SNA','SO','LUV',
		'SPGI','SWK','SBUX','STT','SRCL','SYK','STI','SYMC','SYF','SNPS','SYY','TROW','TPR',
		'TGT','TEL','FTI','TXN','TXT','TMO','TIF','TWX','TJX','TMK','TSS','TSCO','TDG','TRV',
		'TRIP','FOXA','FOX','TSN','UDR','ULTA','USB','UAA','UA','UNP','UAL','UNH','UPS','URI',
		'UTX','UHS','UNM','VFC','VLO','VAR','VTR','VRSN','VRSK','VZ','VRTX','VIAB','V','VNO',
		'VMC','WMT','WBA','DIS','WM','WAT','WEC','WFC','HCN','WDC','WU','WRK','WY','WHR','WMB',
		'WLTW','WYN','WYNN','XEL','XRX','XLNX','XL','XYL','YUM','ZBH','ZION','ZTS']

len(sptickers)

505

For simplicity, I use Quandl's WIKI Price [database](https://www.quandl.com/databases/WIKIP/documentation). Note that the database is not completely up-to-date.

In [ ]:
# Create index for data frame. Dates from 1999-01-01 to 2019-01-01.

index = pd.date_range(start='1999-01-01', end='2019-01-01')
sp500 = pd.DataFrame(index=index)

# Because I can't make too many requests at once, I run a loop through the tickers
for i in sptickers:
    data = quandl.get_table('WIKI/PRICES', ticker = i, 
                        qopts = { 'columns': ['ticker', 'date', 'adj_close'] }, 
                        date = { 'gte': '1999-01-01', 'lte': '2019-01-01' }, 
                        paginate=True)
    
    # Set the row index to date and fill in the ticker
    new = data.set_index('date')
    clean_data = new.pivot(columns='ticker')
    sp500 = sp500.join(clean_data, how="left")
    # Counter for the impatient
    print(sptickers.index(i))
    time.sleep(.1)

In [ ]:
# Drop all observations where the market is not open
sp500v2 = sp500.dropna(axis=0,how='all')
# Clean up the column names
sp500v2.columns = [i[1] for i in sp500v2.columns]
# Save file
sp500v2.to_csv(r"/Users/abikumar/Desktop/Capstone1/SP500.csv")

# S&P 500 Indicators
Let's just see what kind of data we can get from SHARADAR. I'll test it using Apple (AAPL).

In [35]:
data = quandl.get_table('SHARADAR/SF1', ticker = 'AAPL')
data

,ticker,dimension,calendardate,datekey,reportperiod,lastupdated,accoci,assets,assetsavg,assetsc,...,sharesbas,shareswa,shareswadil,sps,tangibles,taxassets,taxexp,taxliabilities,tbvps,workingcapital
None,,,,,,,,,,,,,,,,,,,,,
0,AAPL,MRY,2018-12-31,2018-09-29,2018-09-29,2019-05-01,-3454000000,365725000000,372304500000,131339000000,...,4829926000,4955377000,5000109000,53.597,365725000000,0,13372000000,0,76.168,15410000000
1,AAPL,MRY,2017-12-31,2017-09-30,2017-09-30,2019-05-01,-150000000,375319000000,346541250000,128645000000,...,5165228000,5217242000,5251692000,43.938,375319000000,0,15738000000,0,72.886,27831000000
2,AAPL,MRY,2016-12-31,2016-09-24,2016-09-24,2019-05-01,634000000,321686000000,306462250000,106869000000,...,5388443000,5470820000,5500281000,39.416,313066000000,0,15685000000,0,58.333,27863000000
3,AAPL,MRY,2015-12-31,2015-09-26,2015-09-26,2019-05-01,-345000000,290345000000,271646000000,89378000000,...,5702722000,5753421000,5793069000,40.622,281336000000,0,19121000000,0,49.821,8768000000
4,AAPL,MRY,2014-12-31,2014-09-27,2014-09-27,2019-05-01,1082000000,231839000000,221383000000,68531000000,...,5987867000,6085572000,6122663000,30.037,223081000000,4318000000,13973000000,0,37.595,5083000000
5,AAPL,MRY,2013-12-31,2013-09-28,2013-09-28,2019-05-01,-471000000,207000000000,199421750000,73286000000,...,6359479000,6477320000,6521634000,26.386,201244000000,3453000000,13118000000,0,31.796,29628000000
6,AAPL,MRY,2012-12-31,2012-09-29,2012-09-29,2019-05-01,499000000,176064000000,157143750000,57653000000,...,6561842000,6543726000,6617483000,23.917,170705000000,2583000000,14030000000,0,25.991,19111000000
7,AAPL,MRY,2011-12-31,2011-09-24,2011-09-24,2019-05-01,443000000,116371000000,101193750000,44988000000,...,6489636202,6469806000,6556515000,16.731,111939000000,2014000000,8283000000,0,17.227,17018000000

It seems that, without paying, I can get up to 8 Most-Recently Reported Yearly Data (MRY). The documentation defines Most-Recently reported as "the most recently reported data for thtat reporting period."

In [ ]:
# Create empty dataframe to store results
indicators = pd.DataFrame(columns = data.columns)

# Go through all tickers and get the indicators
for ticker in sptickers:
    data = quandl.get_table('SHARADAR/SF1', ticker = ticker)
    
    indicators = indicators.append(data)
    
    print(sptickers.index(ticker))
    time.sleep(.1)

In [ ]:
indicators.to_csv(r"/Users/abikumar/Desktop/Capstone1/SP500indicators.csv")